<?php
session_start();

    include ("connection.php");
    include ("functions.php");

    if($_SERVER['REQUEST_METHOD'] == 'POST') //checks the request method is POST or not
    {
        $user_name = $_POST['user_name'];  // gets the user name from form data
        $password  = md5($_POST['password']);  // gets the password from form data and convert it to MD5 format

        if(!empty($user_name)  && !empty($password) && !is_numeric($user_name)) // password should be empty and username should not be numeric to prevent malicious
        {
            $user_id = random_num(20); // user id will be generated by this function and it will be a number of length 20
            $query="insert into users (user_id, user_name, password) values('$user_id', '$user_name', '$password' )"; // insert into users table using password and user_name
            
            mysqli_query($con,$query); // update users table using query

            header("Location: login.php"); // after signup it will redirect to login.php
            die;

        }else{
            echo "Please enter details";
        }


    }


?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
    <link rel="stylesheet" href="CSS/signup.css">
</head>
<body>
    
    <div class="container">
        <form action="" method="post" class="signup-form">
            <h2 style="text-align:center">Signup Form</h2>
            <label for="username">Username: </label><br />
            <input type="text" name="user_name"><br>
            <label for="password">Password: </label><br />
            <input type="password" name="password"> <br>
            <input type="submit" name="submit" value="Signup"><br>

           <p class="login-link"> Already a account <a class="login-link" href="login.php" style="text-decoration:none"><b>Login</b></a><br></p>
        </form>
    </div>

</body>
</html>